import { EventBuilds } from '../types/builds';

// Builds organized by Pokemon name for easy lookup
export const buildsConfig: EventBuilds = {
  // Builds for Wo-Chien
  'wo-chien': {
    attackers: [
      {
        pokemonName: "Ceruledge",
        pokemonId: 937,
        variant: "physical-attacker" as const,
        ability: "Flash Fire",
        nature: "Adamant (+Atk, -SpA)",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Metronome",
        moves: ["Bitter Blade", "Sunny Day", "Swords Dance"],
        teraType: "Fire",
        role: "Utilize Bitter Blade for consistent damage and healing. Setting up Sunny Day boosts Fire-type moves, and Swords Dance increases attack power. The Metronome item enhances repeated use of the same move."
      },
      {
        pokemonName: "Slither Wing",
        pokemonId: 988,
        pokemonVariant: "Scarlet",
        variant: "physical-attacker" as const,
        ability: "Protosynthesis",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Metronome",
        moves: ["Leech Life", "Sunny Day", "Morning Sun"],
        teraType: "Bug",
        role: "Leech Life exploits Wo-Chien's 2× Bug weakness while healing Slither Wing. Sunny Day activates Protosynthesis, boosting stats, and Morning Sun provides additional healing."
      },
      {
        pokemonName: "Armarouge",
        pokemonId: 936,
        variant: "special-attacker" as const,
        ability: "Flash Fire",
        nature: "Modest (+SpA, -Atk)",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 4, speed: 0 },
        heldItem: "Covert Cloak",
        moves: ["Acid Spray", "Flamethrower", "Mystical Fire"],
        teraType: "Fire",
        role: "Use Acid Spray to lower Wo-Chien's Special Defense, then follow up with Flamethrower or Mystical Fire for damage. Covert Cloak protects against secondary effects."
      },
      {
        pokemonName: "Iron Moth",
        pokemonId: 994,
        pokemonVariant: "Violet",
        variant: "special-attacker" as const,
        ability: "Quark Drive",
        nature: "Modest",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 4, speed: 0 },
        heldItem: "Booster Energy",
        moves: ["Fiery Dance", "Acid Spray", "Flamethrower"],
        teraType: "Fire",
        role: "Acid Spray lowers Special Defense, setting up for powerful Fiery Dance or Flamethrower attacks. Booster Energy activates Quark Drive, enhancing stats."
      },
      {
        pokemonName: "Skeledirge",
        pokemonId: 911,
        variant: "special-attacker" as const,
        ability: "Blaze",
        nature: "Modest",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 0, speed: 4 },
        heldItem: "Heat Rock",
        moves: ["Sunny Day", "Will-o-Wisp", "Fire Blast", "Shadow Ball"],
        teraType: "Fire",
        role: "Sunny Day boosts Fire moves. Will-o-Wisp cripples physical attackers. Fire Blast/Flamethrower for damage. Shadow Ball/Hex for Ghost STAB. Great synergy with sun teams."
      },
      {
        pokemonName: "Ogerpon",
        pokemonId: 1017,
        pokemonVariant: "Hearthflame Mask",
        variant: "physical-attacker" as const,
        ability: "Mold Breaker",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 4 },
        heldItem: "Hearthflame Mask",
        moves: ["Ivy Cudgel", "Swords Dance", "Horn Leech", "Sunny Day"],
        teraType: "Fire",
        role: "Swords Dance to boost Attack. Ivy Cudgel for strong Fire STAB. Horn Leech for healing. Sunny Day for sun synergy. Mask and Tera Fire amplify damage."
      },
      {
        pokemonName: "Reshiram",
        pokemonId: 643,
        variant: "special-attacker" as const,
        ability: "Turboblaze",
        nature: "Modest (+SpA, -Atk)",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 4, speed: 0 },
        heldItem: "Choice Specs",
        moves: ["Blue Flare", "Fusion Flare", "Draco Meteor", "Earth Power"],
        teraType: "Fire",
        role: "Pure special STAB—huge single-move damage on Grass-Tera Wo-Chien."
      },
      {
        pokemonName: "Ho-Oh",
        pokemonId: 250,
        variant: "physical-attacker" as const,
        ability: "Regenerator",
        nature: "Adamant (+Atk, -SpA)",
        evs: { hp: 248, attack: 252, defense: 0, specialAttack: 0, specialDefense: 8, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Sacred Fire", "Brave Bird", "Sunny Day", "Recover"],
        teraType: "Fire",
        role: "Bulky physical threat that sets sun for your team and heals on switch-out."
      },
      {
        pokemonName: "Heatran",
        pokemonId: 485,
        variant: "special-attacker" as const,
        ability: "Flash Fire",
        nature: "Modest",
        evs: { hp: 4, attack: 0, defense: 0, specialAttack: 252, specialDefense: 0, speed: 252 },
        heldItem: "Choice Specs",
        moves: ["Magma Storm", "Flash Cannon", "Fire Blast", "Earth Power"],
        teraType: "Steel",
        role: "Scarf outspeeds and nukes; Specs packs insane Sun-boosted Fire/Steel damage."
      },
      {
        pokemonName: "Volcanion",
        pokemonId: 721,
        variant: "special-attacker" as const,
        ability: "Water Absorb",
        nature: "Modest (+SpA, -Atk)",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 4, speed: 0 },
        heldItem: "Choice Scarf",
        moves: ["Steam Eruption", "Flamethrower", "Sludge Bomb", "Earth Power"],
        teraType: "Fire",
        role: "Mixed-special attacker that tanks Water hits, sets up Sun via allies, and hits back harder."
      }
    ],
    defenders: [
      {
        pokemonName: "Umbreon",
        pokemonId: 197,
        variant: "physical-wall" as const,
        ability: "Synchronize",
        nature: "Bold (+Def, -Atk)",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Sunny Day", "Helping Hand", "Wish", "Protect"],
        teraType: "Dark",
        role: "Bulky sun setter that also heals teammates with Wish and boosts their damage with Helping Hand."
      },
      {
        pokemonName: "Torkoal",
        pokemonId: 324,
        variant: "physical-wall" as const,
        ability: "Drought",
        nature: "Relaxed (+Def, -Spe)",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Heat Rock",
        moves: ["Lava Plume", "Eruption", "Stealth Rock", "Solar Beam"],
        teraType: "Fire",
        role: "Automatic sun setter on switch-in; can soften Wo-Chien with STAB Fire and pressure with Solar Beam."
      },
      {
        pokemonName: "Grimmsnarl",
        pokemonId: 861,
        variant: "physical-wall" as const,
        ability: "Prankster",
        nature: "Bold (+Def, -Atk)",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Sunny Day", "Light Screen", "Reflect", "Thunder Wave"],
        teraType: "Fairy",
        role: "Prankster-priority dual screens under sun, crippling speed with T-Wave and boosting allies' longevity."
      },
      {
        pokemonName: "Indeedee-F",
        pokemonId: 876,
        variant: "special-wall" as const,
        ability: "Psychic Surge",
        nature: "Modest (+SpA, -Atk)",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 252, specialDefense: 0, speed: 0 },
        heldItem: "Psychic Seed",
        moves: ["Sunny Day", "Helping Hand", "Heal Pulse", "Follow Me"],
        teraType: "Psychic",
        role: "Terrain setter and fast support: draws attacks, heals allies, and boosts damage."
      },
      {
        pokemonName: "Cresselia",
        pokemonId: 488,
        variant: "special-wall" as const,
        ability: "Levitate",
        nature: "Calm (+SpD, -Atk)",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Rocky Helmet",
        moves: ["Sunny Day", "Moonlight", "Light Screen", "Ice Beam"],
        teraType: "Psychic",
        role: "Heavy-hitting support with screens, moonlight healing, and optional coverage."
      },
      {
        pokemonName: "Scream Tail",
        pokemonId: 985,
        variant: "physical-wall" as const,
        ability: "Sweet Veil",
        nature: "Timid (+Spe, -Atk)",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 0, specialDefense: 4, speed: 252 },
        heldItem: "Focus Sash",
        moves: ["Sunny Day", "Helping Hand", "Light Screen", "Play Rough"],
        teraType: "Fairy",
        role: "Fast sun setter that ensures at least one support action with Focus Sash, plus screens and boosts."
      },
      {
        pokemonName: "Chansey",
        pokemonId: 113,
        variant: "special-wall" as const,
        ability: "Natural Cure",
        nature: "Bold (+Def, -Atk)",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Eviolite",
        moves: ["Sunny Day", "Heal Pulse", "Toxic", "Protect"],
        teraType: "Normal",
        role: "Ultra-bulky healer, poisons Wo-Chien, and sets sun—ideal in stall-oriented teams."
      },
      {
        pokemonName: "Toedscruel",
        pokemonId: 949,
        pokemonVariant: "Scarlet",
        variant: "physical-wall" as const,
        ability: "Drought",
        nature: "Relaxed (+Def, -Spe)",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Heat Rock",
        moves: ["Spore", "Sunny Day", "Earthquake", "Stone Edge"],
        teraType: "Ground",
        role: "Sleep abuser with Spore, auto-sun setter, and provides Ground coverage vs. Flying support Pokémon."
      },
      {
        pokemonName: "Alcremie",
        pokemonId: 869,
        variant: "special-wall" as const,
        ability: "Neutralizing Gas",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 4, specialDefense: 252, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Helping Hand", "Decorate", "Recover", "Light Screen"],
        teraType: "Fairy",
        role: "Alcremie uses Decorate to massively power up your attacker(s), sets up Light Screen to reduce incoming special damage, heals itself as needed with Recover, and provides further damage boost with Helping Hand. Neutralizing Gas disables opponent abilities that could interfere."
      },
      {
        pokemonName: "Bellossom",
        pokemonId: 182,
        variant: "special-wall" as const,
        ability: "Healer",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 4, specialDefense: 252, speed: 0 },
        heldItem: "Heat Rock",
        moves: ["Sunny Day", "Moonlight", "Acid Spray", "Helping Hand"],
        teraType: "Grass",
        role: "Bellossom helps establish Sunny Day, boosting Fire attackers. It uses Acid Spray to debuff the boss's Special Defense, supports with Helping Hand, and sustains with Moonlight, benefiting from sunny weather because of Heat Rock."
      }
    ]
  },

  // Chi-Yu Tera Raid Boss (Fire Tera Type)
  'chi-yu': {
    attackers: [
      {
        pokemonName: "Azumarill",
        pokemonId: 184,
        variant: "physical-attacker" as const,
        ability: "Huge Power",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Mystic Water",
        moves: ["Belly Drum", "Liquidation", "Play Rough", "Rain Dance"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "With setup, Azumarill can one-shot or two-shot Chi-Yu. Belly Drum maxes Attack then Liquidation hits Fire Tera Chi-Yu for massive damage. Fairy typing shrugs off Dark Pulse (0.5×). Rain Dance further cuts Chi-Yu's Fire power by 50% and boosts Liquidation."
      },
      {
        pokemonName: "Garchomp",
        pokemonId: 445,
        variant: "physical-attacker" as const,
        ability: "Rough Skin",
        nature: "Jolly",
        evs: { hp: 4, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 252 },
        heldItem: "Soft Sand",
        moves: ["Earthquake", "Dragon Claw", "Swords Dance", "Rock Slide"],
        teraType: "Ground",
        role: "Physical DPS",
        notes: "STAB Earthquake hits Fire Tera Chi-Yu super-effectively (2×) and ignores Beads of Ruin drop on SpDef. After Swords Dance, it can OHKO or severely dent Chi-Yu. Immune to Electric (if boss had Thunderbolt). Needs burn protection (Misty Terrain support) to avoid Wisp halving its Attack."
      },
      {
        pokemonName: "Ting-Lu",
        pokemonId: 1003,
        variant: "physical-attacker" as const,
        ability: "Vessel of Ruin",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Assault Vest",
        moves: ["Earthquake", "Heavy Slam", "Darkest Lariat", "Stomping Tantrum"],
        teraType: "Ground",
        role: "Physical Tank DPS",
        notes: "Naturally tanks Chi-Yu's Dark and Psychic moves (Dark type is immune to Psychic). Its ability lowers Chi-Yu's Sp. Atk by 25% for the team, partially offsetting Beads of Ruin. STAB Earthquake hammers Chi-Yu's Fire Tera. Can terastallize to Ground for extra damage."
      },
      {
        pokemonName: "Heatran",
        pokemonId: 485,
        variant: "special-attacker" as const,
        ability: "Flash Fire",
        nature: "Modest",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 4, speed: 0 },
        heldItem: "Wise Glasses",
        moves: ["Magma Storm", "Earth Power", "Flash Cannon", "Metal Sound"],
        teraType: "Fire",
        role: "Special DPS",
        notes: "Immune to Fire moves (Flash Fire absorbs Lava Plume with no damage and boosts Heatran's own Fire attacks). Steel typing resists Psychic (0.5×) and Dark (neutral). STAB Earth Power (Ground) and Flash Cannon (Steel) both hit Fire Tera Chi-Yu hard. Metal Sound harshly lowers Chi-Yu's SpDef, enabling other special attackers to overcome Beads of Ruin drop. Legendary via HOME."
      },
      {
        pokemonName: "Gyarados",
        pokemonId: 130,
        variant: "physical-attacker" as const,
        ability: "Intimidate",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Shell Bell",
        moves: ["Aqua Tail", "Earthquake", "Dragon Dance", "Crunch"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "Resists Fire (Water 0.5×) and Dark (Crunch 1×). Intimidate cuts Chi-Yu's Attack (mostly irrelevant as it's special) but helps if it uses physical coverage. After a Dragon Dance or two, Aqua Tail (STAB 2× vs Fire) and Earthquake deal huge damage. Shell Bell heals off Lava Plume chip. Watch for Will-O-Wisp burns – consider Misty Terrain support to block burns."
      },
      {
        pokemonName: "Iron Hands",
        pokemonId: 992,
        pokemonVariant: "Violet",
        variant: "physical-attacker" as const,
        ability: "Quark Drive",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Shell Bell",
        moves: ["Drain Punch", "Thunder Punch", "Belly Drum", "Electric Terrain"],
        teraType: "Fighting",
        role: "Physical DPS",
        notes: "Can Belly Drum safely if screens are up, then OHKO Chi-Yu with Drain Punch (super-effective vs Dark typing). Drain Punch also heals off damage. Thunder Punch provides alternative STAB vs Fire if needed (Electric Terrain boosts it). Chi-Yu's Psychic is 2× vs Fighting – set Light Screen or Misty Terrain before Drum."
      },
      {
        pokemonName: "Gastrodon",
        pokemonId: 423,
        variant: "special-attacker" as const,
        ability: "Storm Drain",
        nature: "Sassy",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Rindo Berry",
        moves: ["Earth Power", "Muddy Water", "Recover", "Acid Armor"],
        teraType: "Water",
        role: "Special Tank DPS",
        notes: "Naturally immune to Water (Storm Drain – irrelevant since Chi-Yu has none) and takes 0.5× from Fire (Water resists Fire). STAB Earth Power devastates Fire Tera Chi-Yu. Can spam Muddy Water to hit through Wonder Room (if any) and potentially lower accuracy. Acid Armor counters Beads of Ruin debuff by raising its Def sharply. Very high SpDef + Recover makes it nigh unkillable even under Ruin."
      },
      {
        pokemonName: "Urshifu",
        pokemonId: 892,
        pokemonVariant: "Rapid Strike",
        variant: "physical-attacker" as const,
        ability: "Unseen Fist",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Mystic Water",
        moves: ["Surging Strikes", "Close Combat", "Aqua Jet", "Bulk Up"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "STAB Surging Strikes (always crits) rips through Chi-Yu's massive SpDef drop and deals consistent 2× damage (Water vs Fire) – 3 guaranteed crits ignore stat changes. Resists Fire (Water) and Dark (Fighting), though Psychic is 2× (needs Light Screen support). Bulk Up if time allows; otherwise spam water moves. DLC/home required."
      },
      {
        pokemonName: "Quaquaval",
        pokemonId: 914,
        variant: "physical-attacker" as const,
        ability: "Moxie",
        nature: "Jolly",
        evs: { hp: 4, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 252 },
        heldItem: "Mystic Water",
        moves: ["Aqua Step", "Wave Crash", "Low Kick", "Swords Dance"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "Every Aqua Step hit boosts Quaquaval's Speed, letting it outrun Chi-Yu and avoid flinches. STAB Wave Crash (×2 vs Fire) does huge damage; Low Kick hits original Dark typing if needed. Moxie or Aqua Step boosts can snowball its Attack to high levels. Needs protect from Psychic-type attacks (Fighting weakness)."
      },
      {
        pokemonName: "Clodsire",
        pokemonId: 980,
        variant: "physical-attacker" as const,
        ability: "Unaware",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Earthquake", "Yawn", "Recover", "Curse"],
        teraType: "Ground",
        role: "Special Wall DPS",
        notes: "Unaware ignores Chi-Yu's SpAtk boosts (if it uses Nasty Plot) or stat drops on itself. Clodsire's excellent HP+SpDef lets it tank Dark Pulse and Lava Plume. STAB EQ hits Fire Tera super-effectively. Yawn forces Chi-Yu to drowse then sleep, buying setup turns. Can Curse to raise Attack/Defense (Unaware means it doesn't care about its own lowered SpDef from Ruin). Watch out for Psychic (2× vs Poison-type Clodsire)."
      }
    ],
    defenders: [
      {
        pokemonName: "Pelipper",
        pokemonId: 279,
        variant: "special-wall" as const,
        ability: "Drizzle",
        nature: "Bold",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Damp Rock",
        moves: ["Hurricane", "Wide Guard", "Roost", "U-turn"],
        teraType: "Water",
        role: "Rain Support",
        notes: "Automatically sets Rain on entry (via Drizzle), immediately halving Fire move power and boosting Water moves by 50% (useful for Water attackers) – though Chi-Yu has no Fire moves, rain can help wash away potential Sandstorms. Wide Guard completely blocks Lava Plume from hitting allies each turn. Flying typing avoids Ground moves. Roost to heal."
      },
      {
        pokemonName: "Blissey",
        pokemonId: 242,
        variant: "special-wall" as const,
        ability: "Natural Cure",
        nature: "Bold",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Eviolite",
        moves: ["Life Dew", "Light Screen", "Helping Hand", "Charm"],
        teraType: "Normal",
        role: "Healer",
        notes: "The premier raid healer. Eviolite Blissey is extremely bulky on the special side (can tank Chi-Yu's Ruination and Dark Pulse easily). Life Dew heals entire team by 25% each use. Light Screen halves special damage team-wide. Charm harshly cuts boss's Attack. Helping Hand boosts ally attacks. Keep Blissey protected from repeated special attacks."
      },
      {
        pokemonName: "Grimmsnarl",
        pokemonId: 861,
        variant: "physical-wall" as const,
        ability: "Prankster",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 216, specialAttack: 0, specialDefense: 40, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Taunt", "Reflect", "Light Screen", "Spirit Break"],
        teraType: "Fairy",
        role: "Screen/Disrupt",
        notes: "Priority screens protect team (Reflect/Light Screen). Taunt stops Chi-Yu's Nasty Plot or other setup moves turn 1. Spirit Break is clutch – it lowers boss's Special Attack each use (countering Beads of Ruin). Prankster moves won't affect Dark-type boss (so rely on Spirit Break for debuff)."
      },
      {
        pokemonName: "Umbreon",
        pokemonId: 197,
        variant: "special-wall" as const,
        ability: "Synchronize",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Fake Tears", "Helping Hand", "Snarl", "Moonlight"],
        teraType: "Dark",
        role: "Tank/Support",
        notes: "Immune to Psychic, resists Dark. Can survive even super-effective hits with its bulk. Fake Tears sharply drops boss's SpDef (great for special attackers) – note Dark Tera means Prankster isn't an issue for Umbreon. Snarl reduces boss's SpAtk each hit (useful if it runs special coverage). Helping Hand boosts ally DPS significantly. Moonlight keeps Umbreon healthy."
      },
      {
        pokemonName: "Salamence",
        pokemonId: 373,
        variant: "physical-wall" as const,
        ability: "Intimidate",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Sitrus Berry",
        moves: ["Breaking Swipe", "Roost", "Tailwind", "Scary Face"],
        teraType: "Flying",
        role: "Attack Debuff",
        notes: "Intimidate triggers on entry to lower Chi-Yu's Attack by 1 stage. Flying typing resists Fighting moves (if any) and avoids Ground coverage. Can use Breaking Swipe to further drop boss's Attack every hit. Tailwind doubles team Speed. Needs careful Roost use (loses Flying for 1 turn)."
      },
      {
        pokemonName: "Corviknight",
        pokemonId: 823,
        variant: "physical-wall" as const,
        ability: "Mirror Armor",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Iron Defense", "Body Press", "Screech", "Roost"],
        teraType: "Steel",
        role: "Physical Wall",
        notes: "Flying/Steel typing resists many attacks. Mirror Armor reflects stat drops back at Chi-Yu. After 2–3 Iron Defenses, Corviknight can chip hard with Body Press. Screech support accelerates allies' KOs. Roost stalling works since boss lacks 4× damage output on Corvi."
      },
      {
        pokemonName: "Florges",
        pokemonId: 671,
        variant: "special-wall" as const,
        ability: "Flower Veil",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Misty Terrain", "Wish", "Moonblast", "Protect"],
        teraType: "Fairy",
        role: "Support",
        notes: "Base 154 SpDef lets Florges sponge Ruination and Dark Pulse easily. Misty Terrain prevents allies from being statused and halves damage from boss's potential Dragon moves. Wish + Protect provides 50% HP healing to itself or a switch-in ally after 1 turn. Moonblast can lower Chi-Yu's Attack if needed (30% chance). Fairy typing – immune to Dragon, takes half from Dark."
      },
      {
        pokemonName: "Toxapex",
        pokemonId: 748,
        variant: "physical-wall" as const,
        ability: "Merciless",
        nature: "Bold",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Rocky Helmet",
        moves: ["Wide Guard", "Acid Spray", "Recover", "Haze"],
        teraType: "Water",
        role: "Defender",
        notes: "Wide Guard protects team from multi-target moves like Lava Plume. Acid Spray harshly lowers boss's SpDef (helping allies' special attacks). Extremely high Defense tank. Haze can reset stat changes if Chi-Yu sets up. Recover for reliable healing."
      },
      {
        pokemonName: "Dachsbun",
        pokemonId: 927,
        variant: "special-wall" as const,
        ability: "Well-Baked Body",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Charm", "Howl", "Helping Hand", "Protect"],
        teraType: "Fairy",
        role: "Status Support",
        notes: "Well-Baked Body provides immunity to Fire moves and boosts Defense when hit by them. Charm sharply cuts boss's Attack. Howl raises team's Attack (great with physical attackers). Helping Hand boosts ally damage. Cannot be burned by boss's Will-O-Wisp (Fairy type)."
      },
      {
        pokemonName: "Chansey",
        pokemonId: 113,
        variant: "special-wall" as const,
        ability: "Healer",
        nature: "Bold",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Eviolite",
        moves: ["Life Dew", "Light Screen", "Helping Hand", "Charm"],
        teraType: "Normal",
        role: "Healer",
        notes: "The premier raid healer. Eviolite Chansey is extremely bulky on the special side (can tank Chi-Yu's Ruination and Dark Pulse easily). Life Dew heals entire team by 25% each use. Light Screen halves special damage team-wide. Charm harshly cuts boss's Attack. Helping Hand boosts ally attacks. Keep Chansey protected from repeated special attacks."
      }
    ]
  },

  // Ting-Lu Tera Raid Boss (Ground Tera Type)
  'ting-lu': {
    attackers: [
      {
        pokemonName: "Breloom",
        pokemonId: 286,
        variant: "physical-attacker" as const,
        ability: "Technician",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Fist Plate",
        moves: ["Spore", "Bullet Seed", "Mach Punch", "Swords Dance"],
        teraType: "Grass",
        role: "Physical DPS",
        notes: "4x resists Ground and Rock. Bullet Seed (multi-hit) gets Technician boost; Mach Punch offers priority (super-effective vs Dark). Spore grants easy setup."
      },
      {
        pokemonName: "Azumarill",
        pokemonId: 184,
        variant: "physical-attacker" as const,
        ability: "Huge Power",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Shell Bell",
        moves: ["Belly Drum", "Liquidation", "Play Rough", "Rain Dance"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "Belly Drum + Liquidation can OHKO or 2HKO Ting-Lu. Fairy typing ignores Ruination (immune to Dark) and Play Rough hits original Dark type for 2× damage. Rain further boosts STAB Water and cuts boss's Rock damage."
      },
      {
        pokemonName: "Meowscarada",
        pokemonId: 908,
        variant: "physical-attacker" as const,
        ability: "Overgrow",
        nature: "Jolly",
        evs: { hp: 4, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 252 },
        heldItem: "Miracle Seed",
        moves: ["Flower Trick", "Brick Break", "U-turn", "Swords Dance"],
        teraType: "Grass",
        role: "Physical DPS",
        notes: "Triple resistance: Grass resists Ground & Rock, Dark resists boss's Dark. Flower Trick always crits and never misses, slicing through Vessel of Ruin's SpAtk debuff and any Defense boosts."
      },
      {
        pokemonName: "Mamoswine",
        pokemonId: 473,
        variant: "physical-attacker" as const,
        ability: "Thick Fat",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Muscle Band",
        moves: ["Icicle Crash", "Earthquake", "Ice Shard", "Reflect"],
        teraType: "Ice",
        role: "Physical DPS",
        notes: "Thick Fat halves Fire damage (if present). Icicle Crash hits Ground Tera super-effective (×2). Ice Shard provides priority chip. Weak to boss's Rock Slide, but huge Attack to trade KOs. Pair with support for Reflect to bolster its average Defense."
      },
      {
        pokemonName: "Iron Bundle",
        pokemonId: 991,
        pokemonVariant: "Violet",
        variant: "special-attacker" as const,
        ability: "Quark Drive",
        nature: "Modest",
        evs: { hp: 4, attack: 0, defense: 0, specialAttack: 252, specialDefense: 0, speed: 252 },
        heldItem: "Booster Energy",
        moves: ["Freeze-Dry", "Hydro Pump", "Ice Beam", "Agility"],
        teraType: "Water",
        role: "Special DPS",
        notes: "Extremely fast and hits Ting-Lu's weaknesses. STAB Freeze-Dry (Ice) and Hydro Pump (Water) both 2× vs Ground. Can Agility if needed to outspeed and avoid flinch. High SpAtk partly offset by boss ability. Very frail – needs screen/heal support."
      },
      {
        pokemonName: "Ogerpon",
        pokemonId: 1017,
        pokemonVariant: "Wellspring Mask",
        variant: "physical-attacker" as const,
        ability: "Water Absorb",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Wellspring Mask",
        moves: ["Swords Dance", "Ivy Cudgel", "Horn Leech", "Grassy Terrain"],
        teraType: "Grass",
        role: "Physical DPS",
        notes: "Quadruple resists Ground & Rock moves (Grass/Water typing). Ivy Cudgel is 100 BP physical Grass attack; Horn Leech provides STAB recovery. Water Absorb ability wasted here, but raw power and typing make up for it. DLC required."
      },
      {
        pokemonName: "Gyarados",
        pokemonId: 130,
        variant: "physical-attacker" as const,
        ability: "Intimidate",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Lum Berry",
        moves: ["Dragon Dance", "Waterfall", "Earthquake", "Taunt"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "Immune to Ground moves (Flying type). Intimidate lowers Ting-Lu's Attack by one stage on entry. After a Dragon Dance or two, it can flinch-lock with Waterfall or slam with Earthquake. Must watch for Rock Slide (2× effective). Lum Berry cures potential paralysis from Stun Spore (if boss had such), ensuring setup."
      },
      {
        pokemonName: "Urshifu",
        pokemonId: 891,
        pokemonVariant: "Single Strike",
        variant: "physical-attacker" as const,
        ability: "Unseen Fist",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Black Glasses",
        moves: ["Close Combat", "Wicked Blow", "Drain Punch", "Bulk Up"],
        teraType: "Dark",
        role: "Physical DPS",
        notes: "Immune to Psychic attacks (Dark type). Wicked Blow always crits (ignoring any Defense boosts). Drain Punch adds sustain. Resists boss's Dark attacks 4× (Fighting & Dark) and Rock 2×, but takes neutral Ground. DLC/home required."
      },
      {
        pokemonName: "Tauros",
        pokemonId: 128,
        pokemonVariant: "Paldean Aqua Breed",
        variant: "physical-attacker" as const,
        ability: "Anger Point",
        nature: "Jolly",
        evs: { hp: 4, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 252 },
        heldItem: "Mystic Water",
        moves: ["Wave Crash", "Raging Bull", "Close Combat", "Aqua Jet"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "Paldean Water Tauros quad-resists Rock and resists Dark (Fighting). STAB Wave Crash deals heavy Water damage (×2 vs Ground; beware recoil). Raging Bull (Water) cannot miss and breaks screens. Slight Psychic weakness (Fighting type) offset by high offense and Aqua Jet priority. Violet exclusive (trade if needed)."
      },
      {
        pokemonName: "Virizion",
        pokemonId: 640,
        variant: "physical-attacker" as const,
        ability: "Justified",
        nature: "Jolly",
        evs: { hp: 4, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 252 },
        heldItem: "Miracle Seed",
        moves: ["Leaf Blade", "Sacred Sword", "Swords Dance", "Synthesis"],
        teraType: "Grass",
        role: "Physical DPS",
        notes: "Triple resists Ground, Rock, and Dark moves. Leaf Blade hits Ground Tera super-effectively; Sacred Sword ignores Ting-Lu's Defense boosts. Swords Dance to set up. Needs support to avoid flinches. Transfer via HOME."
      }
    ],
    defenders: [
      {
        pokemonName: "Grimmsnarl",
        pokemonId: 861,
        variant: "physical-wall" as const,
        ability: "Prankster",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 216, specialAttack: 0, specialDefense: 40, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Taunt", "Reflect", "Light Screen", "Spirit Break"],
        teraType: "Fairy",
        role: "Screen/Disrupt",
        notes: "Priority screens protect team (Reflect/Light Screen). Taunt stops Ting-Lu's Bulldoze or Curse (if any) turn 1. Spirit Break is clutch – it lowers boss's Special Attack each use (countering Vessel of Ruin). Prankster moves won't affect Dark-type boss (so rely on Spirit Break for debuff)."
      },
      {
        pokemonName: "Umbreon",
        pokemonId: 197,
        variant: "special-wall" as const,
        ability: "Synchronize",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Fake Tears", "Helping Hand", "Snarl", "Moonlight"],
        teraType: "Dark",
        role: "Tank/Support",
        notes: "Immune to Psychic, resists Dark. Can survive even super-effective hits with its bulk. Fake Tears sharply drops boss's SpDef (great for special attackers) – note Dark Tera means Prankster isn't an issue for Umbreon. Snarl reduces boss's SpAtk each hit (useful if it runs special coverage). Helping Hand boosts ally DPS significantly. Moonlight keeps Umbreon healthy."
      },
      {
        pokemonName: "Salamence",
        pokemonId: 373,
        variant: "physical-wall" as const,
        ability: "Intimidate",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Sitrus Berry",
        moves: ["Breaking Swipe", "Roost", "Tailwind", "Scary Face"],
        teraType: "Flying",
        role: "Attack Debuff",
        notes: "Intimidate triggers on entry to lower Ting-Lu's Attack by 1 stage. Ground moves can't hit Salamence (Flying type), enabling safe Breaking Swipe usage to further drop boss's Attack every hit (–1 Attack to Ting-Lu on each use to all foes) even through shields. Tailwind doubles team Speed. Needs careful Roost use (loses Flying for 1 turn)."
      },
      {
        pokemonName: "Corviknight",
        pokemonId: 823,
        variant: "physical-wall" as const,
        ability: "Mirror Armor",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Iron Defense", "Body Press", "Screech", "Roost"],
        teraType: "Steel",
        role: "Physical Wall",
        notes: "Flying type is immune to Ground. Mirror Armor reflects Ting-Lu's Rock Slide flinch accuracy drop back at it (and any Defense drops from potential Crunch). After 2–3 Iron Defenses, Corviknight can chip hard with Body Press. Screech support accelerates allies' KOs. Roost stalling works since boss lacks 4× damage output on Corvi (Rock Slide only neutral)."
      },
      {
        pokemonName: "Brute Bonnet",
        pokemonId: 986,
        pokemonVariant: "Scarlet",
        variant: "special-wall" as const,
        ability: "Mycelium Might",
        nature: "Sassy",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Spore", "Growth", "Giga Drain", "Synthesis"],
        teraType: "Grass",
        role: "Status/Drain",
        notes: "Resists Ground & Dark (Grass resists Ground, Dark type resists Dark moves). Spore reliably sleeps Ting-Lu for a couple of turns (bypasses ability shields), allowing team to set up safely. Giga Drain can slowly chip and heal Bonnet. Synthesis for emergency self-recovery; Growth if free turns. Needs protection vs Rock Slide (4× effective bug/grass)."
      },
      {
        pokemonName: "Orthworm",
        pokemonId: 968,
        variant: "physical-wall" as const,
        ability: "Earth Eater",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Rocky Helmet",
        moves: ["Iron Defense", "Screech", "Sandstorm", "Body Press"],
        teraType: "Steel",
        role: "Ground Absorb",
        notes: "Orthworm's Earth Eater makes it heal from Ground moves instead of taking damage. It can completely shut down Ting-Lu's STAB Earthquake – each Earthquake actually restores Orthworm's HP. Use Iron Defense to become nearly unbreakable physically, and Screech to support allies. Avoid special hits (Ting-Lu's Throat Chop is neutral)."
      },
      {
        pokemonName: "Toedscruel",
        pokemonId: 949,
        pokemonVariant: "Scarlet",
        variant: "special-wall" as const,
        ability: "Mycelium Might",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Big Root",
        moves: ["Spore", "Reflect", "Leech Seed", "Mud Shot"],
        teraType: "Ground",
        role: "Status/Support",
        notes: "Ground/Grass typing quad-resists Ground and double-resists Rock. Can't be outsped on status moves due to Mycelium Might (so Spore will always land, albeit acting last). Sleeps boss and sets Leech Seed for passive healing. Reflect covers Dark-type physical hits. Mud Shot lowers boss's Speed each hit. Weak only to boss's Dark attacks (neutral) – handled by its high SpDef."
      },
      {
        pokemonName: "Chansey",
        pokemonId: 113,
        variant: "special-wall" as const,
        ability: "Healer",
        nature: "Bold",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Eviolite",
        moves: ["Life Dew", "Light Screen", "Helping Hand", "Charm"],
        teraType: "Normal",
        role: "Healer",
        notes: "The premier raid healer. Eviolite Chansey is extremely bulky on the special side (can tank Ting-Lu's Ruination and Throat Chop easily). Life Dew heals entire team by 25% each use. Light Screen halves special damage team-wide. Charm harshly cuts boss's Attack. Helping Hand boosts ally attacks. Keep Chansey protected from repeated Rock Slides (physical)."
      },
      {
        pokemonName: "Pelipper",
        pokemonId: 279,
        variant: "special-wall" as const,
        ability: "Drizzle",
        nature: "Bold",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Damp Rock",
        moves: ["Wide Guard", "Hurricane", "Roost", "U-turn"],
        teraType: "Water",
        role: "Rain Support",
        notes: "Automatically sets Rain on entry (via Drizzle), immediately halving Fire move power and boosting Water moves by 50% (useful for Water attackers) – though Ting-Lu has no Fire moves, rain can help wash away potential Sandstorms. Wide Guard completely blocks Rock Slide and Earthquake from hitting allies each turn. Flying typing avoids Ground moves. Roost to heal."
      },
      {
        pokemonName: "Florges",
        pokemonId: 671,
        variant: "special-wall" as const,
        ability: "Flower Veil",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Misty Terrain", "Wish", "Moonblast", "Protect"],
        teraType: "Fairy",
        role: "Support",
        notes: "Base 154 SpDef lets Florges sponge Ruination and Throat Chop easily. Misty Terrain prevents allies from being statused and halves damage from boss's potential Dragon Tail (if it had one). Wish + Protect provides 50% HP healing to itself or a switch-in ally after 1 turn. Moonblast can lower Ting-Lu's Attack if needed (30% chance). Fairy typing – immune to Dragon, takes half from Dark."
      }
    ]
  },

  // Chien-Pao Tera Raid Boss (Ice Tera Type)
  'chien-pao': {
    attackers: [
      {
        pokemonName: "Iron Hands",
        pokemonId: 992,
        pokemonVariant: "Violet",
        variant: "physical-attacker" as const,
        ability: "Quark Drive",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Metronome",
        moves: ["Belly Drum", "Drain Punch", "Focus Energy", "Electric Terrain"],
        teraType: "Fighting",
        role: "Physical DPS",
        notes: "Top counter – Belly Drum + Drain Punch for huge damage. Resists Dark. Electric Terrain activates Quark Drive for stat boosts."
      },
      {
        pokemonName: "Slither Wing",
        pokemonId: 988,
        pokemonVariant: "Scarlet",
        variant: "physical-attacker" as const,
        ability: "Protosynthesis",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Metronome",
        teraType: "Fighting",
        moves: ["Leech Life", "Close Combat", "Bulk Up", "Sunny Day"],
        role: "Sunny Day activates Protosynthesis on turn 1, then Bulk Up boosts Attack and Bulk; use Close Combat as your primary STAB to hit Chien‑Pao for 4× damage, with Leech Life optionally healing while exploiting its Dark/Ice neutral or resisted bug matchup."
      },
      {
        pokemonName: "Ceruledge",
        pokemonId: 937,
        variant: "physical-attacker" as const,
        ability: "Flash Fire",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Metronome",
        moves: ["Bitter Blade", "Close Combat", "Will-O-Wisp", "Protect"],
        teraType: "Fire",
        role: "Physical DPS",
        notes: "Immune to Sacred Sword (Ghost type). Bitter Blade provides STAB healing (super-effective vs Ice). Beware Dark Pulse weakness. Will-O-Wisp can cripple physical attackers on the boss's team."
      },
      {
        pokemonName: "Avalugg",
        pokemonId: 713,
        pokemonVariant: "Hisuian",
        variant: "physical-attacker" as const,
        ability: "Ice Body",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Shell Bell",
        moves: ["Iron Defense", "Body Press", "Chilling Water", "Recover"],
        teraType: "Fighting",
        role: "Physical Tank DPS",
        notes: "Massive Defense; Iron Defense + Body Press hits hard. Can Terastallize to Fighting for +STAB. Chilling Water lowers boss's Attack. Ice Body provides passive healing in hail/snow."
      },
      {
        pokemonName: "Urshifu",
        pokemonId: 892,
        pokemonVariant: "Rapid Strike",
        variant: "physical-attacker" as const,
        ability: "Unseen Fist",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Mystic Water",
        moves: ["Swords Dance", "Drain Punch", "Surging Strikes", "Rain Dance"],
        teraType: "Water",
        role: "Physical DPS",
        notes: "Resists Ice & Dark. Drain Punch for sustain, Surging Strikes always crit. DLC/home transfer required. Rain Dance can help team and boost Water moves."
      },
      {
        pokemonName: "Poliwrath",
        pokemonId: 62,
        variant: "physical-attacker" as const,
        ability: "Water Absorb",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Black Belt",
        moves: ["Belly Drum", "Drain Punch", "Chilling Water", "Rain Dance"],
        teraType: "Fighting",
        role: "Physical DPS/Tank",
        notes: "Resists Ice & Dark. Belly Drum + Drain Punch combo for huge damage. DLC (Kitakami) required. Water Absorb heals from Water moves."
      },
      {
        pokemonName: "Cobalion",
        pokemonId: 638,
        variant: "physical-attacker" as const,
        ability: "Justified",
        nature: "Impish",
        evs: { hp: 252, attack: 4, defense: 252, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Lum Berry",
        moves: ["Iron Defense", "Body Press", "Screech", "Reflect"],
        teraType: "Fighting",
        role: "Physical Tank DPS",
        notes: "Quadruple resists boss's Dark and Rock moves. Iron Defense + Body Press strategy. Screech aids team DPS. Transfer via HOME. Justified boosts Attack when hit by Dark moves."
      },
      {
        pokemonName: "Zamazenta",
        pokemonId: 889,
        pokemonVariant: "Hero",
        variant: "physical-attacker" as const,
        ability: "Dauntless Shield",
        nature: "Impish",
        evs: { hp: 252, attack: 4, defense: 252, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Shell Bell",
        moves: ["Iron Defense", "Body Press", "Crunch", "Reflect"],
        teraType: "Fighting",
        role: "Physical Tank DPS",
        notes: "Free +1 Defense on start. Iron Defense + Body Press combo. HOME transfer needed. Immune to stat drops when Crowned. Dauntless Shield provides immediate Defense boost."
      },
      {
        pokemonName: "Annihilape",
        pokemonId: 979,
        variant: "physical-attacker" as const,
        ability: "Defiant",
        nature: "Adamant",
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Shell Bell",
        moves: ["Bulk Up", "Drain Punch", "Rage Fist", "Screech"],
        teraType: "Fighting",
        role: "Physical DPS/Tank",
        notes: "Immune to Sacred Sword (Ghost). Rage Fist grows stronger each hit. Screech support. Resists Dark (Fighting). Neutral to Ice. Defiant boosts Attack when stats are lowered."
      },
      {
        pokemonName: "Volcarona",
        pokemonId: 637,
        variant: "special-attacker" as const,
        ability: "Flame Body",
        nature: "Modest",
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 4, speed: 0 },
        heldItem: "Covert Cloak",
        moves: ["Quiver Dance", "Flamethrower", "Bug Buzz", "Morning Sun"],
        teraType: "Fire",
        role: "Special DPS",
        notes: "Resists Ice (Fire) and Sacred Sword (Bug). Quiver Dance boosts let it sweep. Covert Cloak prevents Icy Wind's speed drop. Flame Body can burn on contact."
      }
    ],
    defenders: [
      {
        pokemonName: "Quaquaval",
        pokemonId: 914,
        variant: "physical-wall" as const,
        ability: "Moxie",
        nature: "Impish",
        evs: { hp: 252, attack: 4, defense: 252, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Helping Hand", "Coaching", "Roost", "Chilling Water"],
        teraType: "Water",
        role: "Buff/Debuff",
        notes: "Resists Dark & Ice. Coaching boosts allies' Attack/Defense (great for Body Press or Drain Punch users). Chilling Water lowers Chien-Pao's Attack. Moxie can boost Attack on KOs."
      },
      {
        pokemonName: "Lucario",
        pokemonId: 448,
        variant: "physical-wall" as const,
        ability: "Inner Focus",
        nature: "Impish",
        evs: { hp: 252, attack: 4, defense: 252, specialAttack: 0, specialDefense: 0, speed: 0 },
        heldItem: "Wide Lens",
        moves: ["Life Dew", "Screech", "Helping Hand", "Coaching"],
        teraType: "Fighting",
        role: "Healer/Buffer",
        notes: "Resists Dark. Life Dew provides team healing. Screech + Coaching amplify allied damage (perfect for Fighting move spam). Wide Lens helps Screech accuracy. Inner Focus prevents flinching."
      },
      {
        pokemonName: "Grimmsnarl",
        pokemonId: 861,
        variant: "special-wall" as const,
        ability: "Prankster",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Reflect", "Light Screen", "Misty Terrain", "Spirit Break"],
        teraType: "Fairy",
        role: "Screen Setter",
        notes: "Dual screens halve physical & special damage taken by the team. Misty Terrain blocks status (e.g. potential secondary effects). Spirit Break drops Chien-Pao's Special Attack each hit. Prankster priority fails on Dark-type foe for status moves (can't Taunt Chien-Pao)."
      },
      {
        pokemonName: "Toxapex",
        pokemonId: 748,
        variant: "physical-wall" as const,
        ability: "Merciless",
        nature: "Bold",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Rocky Helmet",
        moves: ["Wide Guard", "Acid Spray", "Recover", "Chilling Water"],
        teraType: "Water",
        role: "Defender",
        notes: "Wide Guard protects team from multi-target moves like Icy Wind or Avalanches. Acid Spray harshly lowers boss's SpDef (helping allies' special attacks). Extremely high Defense tank. Chilling Water lowers Attack."
      },
      {
        pokemonName: "Sylveon",
        pokemonId: 700,
        variant: "special-wall" as const,
        ability: "Pixilate",
        nature: "Calm",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Sitrus Berry",
        moves: ["Baby-Doll Eyes", "Helping Hand", "Yawn", "Draining Kiss"],
        teraType: "Fairy",
        role: "Debuff/Healer",
        notes: "Fairy typing halves Dark damage. Baby-Doll Eyes (priority) lowers Attack. Yawn induces sleep (after a turn) to neutralize Chien-Pao temporarily. Draining Kiss for self-healing. Pixilate boosts Normal moves."
      },
      {
        pokemonName: "Dachsbun",
        pokemonId: 927,
        variant: "special-wall" as const,
        ability: "Well-Baked Body",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Charm", "Howl", "Helping Hand", "Protect"],
        teraType: "Fairy",
        role: "Status Support",
        notes: "Immune to Ice moves (Well-Baked Body triggers if hit by Fire, not relevant here – but no Fire moves present). Charm sharply cuts boss's Attack. Howl raises team's Attack (great with physical attackers). Cannot be burned by boss's Icy Wind secondary (Fairy type)."
      },
      {
        pokemonName: "Corviknight",
        pokemonId: 823,
        variant: "physical-wall" as const,
        ability: "Mirror Armor",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Iron Defense", "Screech", "Roost", "Body Press"],
        teraType: "Steel",
        role: "Tank/Utility",
        notes: "High Defense and Mirror Armor reflect Defense drops back at Chien-Pao. Can bait and tank hits then Body Press (after Iron Defense) for solid damage. Screech helps allies. Roost heals self (use carefully vs Sacred Sword)."
      },
      {
        pokemonName: "Mimikyu",
        pokemonId: 778,
        variant: "physical-wall" as const,
        ability: "Disguise",
        nature: "Impish",
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 0, specialDefense: 4, speed: 0 },
        heldItem: "Light Clay",
        moves: ["Charm", "Screech", "Taunt", "Protect"],
        teraType: "Ghost",
        role: "Debuff",
        notes: "Disguise lets it tank one hit for free. Ghost typing nullifies Sacred Sword. Charm & Screech sharply debuff boss Attack or Defense as needed. Taunt prevents any buff moves (if boss had). Light Clay if running Screens instead is also an option."
      },
      {
        pokemonName: "Brute Bonnet",
        pokemonId: 986,
        pokemonVariant: "Scarlet",
        variant: "special-wall" as const,
        ability: "Mycelium Might",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Big Root",
        moves: ["Spore", "Synthesis", "Stun Spore", "Seed Bomb"],
        teraType: "Grass",
        role: "Ailment Inflictor",
        notes: "Grass/Dark resists Ground and Dark moves, though weak to boss's Ice. Spore (100% sleep) reliably puts Chien-Pao to sleep (Mycelium Might ensures status works unimpeded by abilities). Can heal with Synthesis and even paralyze with Stun Spore after wake. Use carefully to avoid Ice attacks."
      },
      {
        pokemonName: "Umbreon",
        pokemonId: 197,
        variant: "special-wall" as const,
        ability: "Synchronize",
        nature: "Careful",
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        heldItem: "Leftovers",
        moves: ["Screech", "Helping Hand", "Snarl", "Moonlight"],
        teraType: "Dark",
        role: "Team Support",
        notes: "Double resists Dark moves. Screech greatly lowers boss Defense for allies. Snarl lowers boss's Special Attack every hit (useful if boss runs Icy Wind). Moonlight heals itself. Synchronize can bounce status (if boss tried to Frostbite from Icy Wind drop – not applicable in Gen9)."
      }
    ]
  }
};

// Helper function to get builds for a specific Pokemon event
export const getBuildsForEvent = (eventKey: string) => {
  return buildsConfig[eventKey as keyof typeof buildsConfig] || { attackers: [], defenders: [] };
};
