import { Builds } from '~/types/builds';

export const teraBuildsTop50: Builds = {
  'Top Tera Raid Pokémon Builds': {
    attackers: [
      {
        pokemonName: 'Iron Hands',
        pokemonId: 992,
        pokemonVariant: 'Belly Drum Attacker',
        variant: 'physical-attacker',
        ability: 'Quark Drive',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Shell Bell',
        moves: ['Belly Drum', 'Drain Punch', 'Thunder Punch', 'Close Combat'],
        teraType: 'Fighting',
        role: 'Physical Attacker',
        notes: 'Iron Hands is a powerhouse capable of one-shotting many 5★ and 6★ raid bosses when set up properly. Belly Drum turn 1, then Drain Punch for recovery and damage.',
      },
      {
        pokemonName: 'Koraidon',
        pokemonId: 1007,
        pokemonVariant: 'All-Round Physical Attacker',
        variant: 'physical-attacker',
        ability: 'Orichalcum Pulse',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Black Belt',
        moves: ['Collision Course', 'Drain Punch', 'Screech', 'Fire Fang'],
        teraType: 'Fighting',
        role: 'Physical Attacker',
        notes: 'Koraidon’s Orichalcum Pulse boosts Attack and sets Sun. Use Screech to lower boss Defense, then Collision Course and Drain Punch for damage and sustain.',
      },
      {
        pokemonName: 'Azumarill',
        pokemonId: 184,
        pokemonVariant: 'Huge Power Belly Drum',
        variant: 'physical-attacker',
        ability: 'Huge Power',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Shell Bell',
        moves: ['Belly Drum', 'Play Rough', 'Liquidation', 'Helping Hand'],
        teraType: 'Fairy',
        role: 'Physical Attacker',
        notes: 'Azumarill uses Belly Drum and Huge Power to reach massive Attack. Play Rough is main STAB, Liquidation for coverage, Helping Hand for support.',
      },
      {
        pokemonName: 'Annihilape',
        pokemonId: 979,
        pokemonVariant: 'Bulk Up + Rage Fist',
        variant: 'physical-attacker',
        ability: 'Defiant',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Metronome',
        moves: ['Rage Fist', 'Close Combat', 'Bulk Up', 'Drain Punch'],
        teraType: 'Ghost',
        role: 'Physical Attacker',
        notes: 'Rage Fist grows stronger each time Annihilape is hit. Bulk Up for setup, then Rage Fist for huge damage. Metronome boosts repeated Rage Fist.',
      },
      {
        pokemonName: 'Ceruledge',
        pokemonId: 937,
        pokemonVariant: 'Swords Dance Life-Steal',
        variant: 'physical-attacker',
        ability: 'Flash Fire',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Leftovers',
        moves: ['Bitter Blade', 'Phantom Force', 'Shadow Claw', 'Swords Dance'],
        teraType: 'Fire',
        role: 'Physical Attacker',
        notes: 'Ceruledge uses Bitter Blade for healing and Swords Dance for setup. Flash Fire gives immunity to Fire moves. Leftovers for passive healing.',
      },
      {
        pokemonName: 'Tinkaton',
        pokemonId: 959,
        pokemonVariant: 'Gigaton Hammer Offense',
        variant: 'physical-attacker',
        ability: 'Mold Breaker',
        nature: 'Adamant',
        evs: { hp: 128, attack: 252, defense: 0, specialAttack: 0, specialDefense: 128, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Assault Vest',
        moves: ['Gigaton Hammer', 'Play Rough', 'Swords Dance', 'Fake Tears'],
        teraType: 'Steel',
        role: 'Physical Attacker',
        notes: 'Tinkaton uses Gigaton Hammer for burst, Play Rough for coverage, Swords Dance for setup, and Fake Tears for support. Assault Vest for bulk.',
      },
      {
        pokemonName: 'Garchomp',
        pokemonId: 445,
        pokemonVariant: 'Swords Dance Sweeper',
        variant: 'physical-attacker',
        ability: 'Rough Skin',
        nature: 'Adamant',
        evs: { hp: 4, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 252 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 0, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Clear Amulet',
        moves: ['Earthquake', 'Dragon Claw', 'Swords Dance', 'Stone Edge'],
        teraType: 'Ground',
        role: 'Physical Attacker',
        notes: 'Garchomp uses Swords Dance to boost Attack, then sweeps with Earthquake. Clear Amulet prevents stat drops. Stone Edge for coverage.',
      },
      {
        pokemonName: 'Cetitan',
        pokemonId: 975,
        pokemonVariant: 'Belly Drum Sweeper',
        variant: 'physical-attacker',
        ability: 'Slush Rush',
        nature: 'Adamant',
        evs: { hp: 0, attack: 252, defense: 88, specialAttack: 0, specialDefense: 168, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Shell Bell',
        moves: ['Belly Drum', 'Ice Spinner', 'Earthquake', 'Play Rough'],
        teraType: 'Ice',
        role: 'Physical Attacker',
        notes: 'Cetitan uses Belly Drum for max Attack, Ice Spinner for STAB, Earthquake for coverage, Play Rough for Fighting-types. Shell Bell for healing.',
      },
      {
        pokemonName: 'Kingambit',
        pokemonId: 983,
        pokemonVariant: 'Sword of the Ruled',
        variant: 'physical-attacker',
        ability: 'Supreme Overlord',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 0, specialAttack: 0, specialDefense: 4, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Black Glasses',
        moves: ['Kowtow Cleave', 'Iron Head', 'Swords Dance', 'Screech'],
        teraType: 'Dark',
        role: 'Physical Attacker',
        notes: 'Kingambit uses Swords Dance for setup, Kowtow Cleave for reliable damage, Iron Head for coverage, Screech for support. Black Glasses boost Dark moves.',
      },
      {
        pokemonName: 'Scizor',
        pokemonId: 212,
        pokemonVariant: 'Technician Swords Dance',
        variant: 'physical-attacker',
        ability: 'Technician',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Clear Amulet',
        moves: ['Bullet Punch', 'X-Scissor', 'Swords Dance', 'Leer'],
        teraType: 'Steel',
        role: 'Physical Attacker',
        notes: 'Scizor uses Swords Dance for setup, Bullet Punch for priority, X-Scissor for coverage, Leer for support. Clear Amulet prevents stat drops.',
      },
      {
        pokemonName: 'Ursaluna',
        pokemonId: 901,
        pokemonVariant: 'Guts Facade Bruiser',
        variant: 'physical-attacker',
        ability: 'Guts',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 0 },
        level: 100,
        heldItem: 'Flame Orb',
        moves: ['Belly Drum', 'Facade', 'Drain Punch', 'Earthquake'],
        teraType: 'Normal',
        role: 'Physical Attacker',
        notes: 'Ursaluna uses Flame Orb to activate Guts, Belly Drum for max Attack, Facade for huge damage, Drain Punch for healing, Earthquake for coverage.',
      },
      {
        pokemonName: 'Calyrex',
        pokemonId: 898,
        pokemonVariant: 'Swords Dance Avalanche',
        variant: 'physical-attacker',
        ability: 'As One (Glastrier)',
        nature: 'Brave',
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 0 },
        level: 100,
        heldItem: 'Weakness Policy',
        moves: ['Swords Dance', 'Avalanche', 'High Horsepower', 'Life Dew'],
        teraType: 'Ice',
        role: 'Physical Attacker',
        notes: 'Calyrex-Ice uses Swords Dance for setup, Avalanche for damage (doubles if hit), High Horsepower for coverage, Life Dew for healing.',
      },
      {
        pokemonName: 'Baxcalibur',
        pokemonId: 998,
        pokemonVariant: 'Dragon Dance All-Out Attacker',
        variant: 'physical-attacker',
        ability: 'Thermal Exchange',
        nature: 'Adamant',
        evs: { hp: 4, attack: 252, defense: 0, specialAttack: 0, specialDefense: 0, speed: 252 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Shell Bell',
        moves: ['Glaive Rush', 'Icicle Crash', 'Dragon Dance', 'Crunch'],
        teraType: 'Dragon',
        role: 'Physical Attacker',
        notes: 'Baxcalibur uses Dragon Dance for setup, Glaive Rush for huge damage, Icicle Crash for coverage, Crunch for Ghost/Psychic types.',
      },
      {
        pokemonName: 'Urshifu',
        pokemonId: 892,
        pokemonVariant: 'Wicked One-Punch Bear',
        variant: 'physical-attacker',
        ability: 'Unseen Fist',
        nature: 'Adamant',
        evs: { hp: 252, attack: 252, defense: 4, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Life Orb',
        moves: ['Swords Dance', 'Wicked Blow', 'Drain Punch', 'Close Combat'],
        teraType: 'Dark',
        role: 'Physical Attacker',
        notes: 'Urshifu uses Swords Dance for setup, Wicked Blow for guaranteed crits, Drain Punch for healing, Close Combat for coverage.',
      },
      // --- Special Attackers ---
      {
        pokemonName: 'Miraidon',
        pokemonId: 1008,
        pokemonVariant: 'Electro Drift Special Sweeper',
        variant: 'special-attacker',
        ability: 'Hadron Engine',
        nature: 'Modest',
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 252, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Magnet',
        moves: ['Electro Drift', 'Metal Sound', 'Parabolic Charge', 'Dragon Pulse'],
        teraType: 'Electric',
        role: 'Special Attacker',
        notes: 'Miraidon dominates raids with Hadron Engine and Electro Drift. Metal Sound for Sp. Def drop, Parabolic Charge for healing.',
      },
      {
        pokemonName: 'Sylveon',
        pokemonId: 700,
        pokemonVariant: 'Pixelate Throat Spray Sweeper',
        variant: 'special-attacker',
        ability: 'Pixilate',
        nature: 'Modest',
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 252, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Throat Spray',
        moves: ['Hyper Voice', 'Moonblast', 'Calm Mind', 'Fake Tears'],
        teraType: 'Fairy',
        role: 'Special Attacker',
        notes: 'Sylveon uses Pixilate Hyper Voice and Throat Spray for SpA boost. Calm Mind for setup, Fake Tears for support.',
      },
      {
        pokemonName: 'Gholdengo',
        pokemonId: 1000,
        pokemonVariant: 'Nasty Plot Golden Go',
        variant: 'special-attacker',
        ability: 'Good as Gold',
        nature: 'Modest',
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 252, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Leftovers',
        moves: ['Make It Rain', 'Nasty Plot', 'Shadow Ball', 'Metal Sound'],
        teraType: 'Steel',
        role: 'Special Attacker',
        notes: 'Gholdengo is immune to status, sets up with Nasty Plot, and sweeps with Make It Rain. Metal Sound for Sp. Def drop.',
      },
      {
        pokemonName: 'Flutter Mane',
        pokemonId: 987,
        pokemonVariant: 'Calm Mind Moonblast',
        variant: 'special-attacker',
        ability: 'Protosynthesis',
        nature: 'Modest',
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 252, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Booster Energy',
        moves: ['Moonblast', 'Draining Kiss', 'Calm Mind', 'Fake Tears'],
        teraType: 'Fairy',
        role: 'Special Attacker',
        notes: 'Flutter Mane uses Calm Mind and Protosynthesis for SpA boost, Moonblast for damage, Draining Kiss for healing.',
      },
      {
        pokemonName: 'Espathra',
        pokemonId: 956,
        pokemonVariant: 'Lumina Crash Debuffer',
        variant: 'special-attacker',
        ability: 'Opportunist',
        nature: 'Timid',
        evs: { hp: 104, attack: 0, defense: 136, specialAttack: 252, specialDefense: 0, speed: 16 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Shell Bell',
        moves: ['Lumina Crash', 'Roost', 'Calm Mind', 'Feather Dance'],
        teraType: 'Psychic',
        role: 'Special Attacker / Support',
        notes: 'Espathra debuffs Sp. Def with Lumina Crash, sets up with Calm Mind, and heals with Roost.',
      },
      {
        pokemonName: 'Armarouge',
        pokemonId: 936,
        pokemonVariant: 'Stored Power Soloist',
        variant: 'special-attacker',
        ability: 'Flash Fire',
        nature: 'Modest',
        evs: { hp: 252, attack: 0, defense: 252, specialAttack: 4, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 0, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Twisted Spoon',
        moves: ['Iron Defense', 'Calm Mind', 'Stored Power', 'Acid Spray'],
        teraType: 'Psychic',
        role: 'Special Attacker',
        notes: 'Armarouge sets up with Iron Defense and Calm Mind, then sweeps with Stored Power. Acid Spray for Sp. Def drop.',
      },
      {
        pokemonName: 'Magnezone',
        pokemonId: 462,
        pokemonVariant: 'Analytic All-Rounder',
        variant: 'special-attacker',
        ability: 'Analytic',
        nature: 'Modest',
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 252, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Metal Coat',
        moves: ['Thunderbolt', 'Flash Cannon', 'Metal Sound', 'Light Screen'],
        teraType: 'Steel',
        role: 'Special Attacker / Support',
        notes: 'Magnezone uses Analytic for power, Metal Sound for Sp. Def drop, and Light Screen for team support.',
      },
      {
        pokemonName: 'Polteageist',
        pokemonId: 855,
        pokemonVariant: 'Shell Smash Sweeper',
        variant: 'special-attacker',
        ability: 'Cursed Body',
        nature: 'Modest',
        evs: { hp: 4, attack: 0, defense: 0, specialAttack: 252, specialDefense: 0, speed: 252 },
        ivs: { hp: 31, attack: 0, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'White Herb',
        moves: ['Shell Smash', 'Stored Power', 'Shadow Ball', 'Giga Drain'],
        teraType: 'Psychic',
        role: 'Special Attacker',
        notes: 'Polteageist sets up with Shell Smash, then sweeps with Stored Power. White Herb negates defense drops.',
      },
      {
        pokemonName: 'Iron Moth',
        pokemonId: 994,
        pokemonVariant: 'Acid Spray Special Attacker',
        variant: 'special-attacker',
        ability: 'Quark Drive',
        nature: 'Modest',
        evs: { hp: 252, attack: 0, defense: 0, specialAttack: 252, specialDefense: 0, speed: 4 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Booster Energy',
        moves: ['Acid Spray', 'Fiery Dance', 'Hurricane', 'Energy Ball'],
        teraType: 'Fire',
        role: 'Special Attacker / Debuffer',
        notes: 'Iron Moth uses Acid Spray for Sp. Def drop, Fiery Dance for damage and SpA boost, Booster Energy for Quark Drive.',
      },
    ],
    defenders: [
      {
        pokemonName: 'Zamazenta',
        pokemonId: 889,
        pokemonVariant: 'Iron Defense Body Press Tank',
        variant: 'physical-wall',
        ability: 'Dauntless Shield',
        nature: 'Impish',
        evs: { hp: 252, attack: 4, defense: 252, specialAttack: 0, specialDefense: 0, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Leftovers',
        moves: ['Iron Defense', 'Body Press', 'Brick Break', 'Reflect'],
        teraType: 'Fighting',
        role: 'Physical Attacker (Defensive)',
        notes: 'Zamazenta uses Iron Defense to boost Defense, then Body Press for damage. Dauntless Shield gives +1 Def on entry. Leftovers for healing.',
      },
      {
        pokemonName: 'Gothitelle',
        pokemonId: 576,
        pokemonVariant: 'Supportive Specialist',
        variant: 'special-wall',
        ability: 'Competitive',
        nature: 'Calm',
        evs: { hp: 252, attack: 0, defense: 4, specialAttack: 0, specialDefense: 252, speed: 0 },
        ivs: { hp: 31, attack: 31, defense: 31, specialAttack: 31, specialDefense: 31, speed: 31 },
        level: 100,
        heldItem: 'Light Clay',
        moves: ['Fake Tears', 'Psychic', 'Charm', 'Light Screen'],
        teraType: 'Psychic',
        role: 'Special Attacker / Support',
        notes: 'Gothitelle supports with Fake Tears, Charm, and Light Screen. Competitive boosts SpA if stats are lowered.',
      },
    ],
  },
};
