import { MysteryGiftEvent, EventType } from './types';

/**
 * Mystery Gift Events
 * Special distributions of Pokemon, items, or content unlocks
 */
export const mysteryGiftEvents: Record<string, MysteryGiftEvent> = {
  'mewtwonite-legends-za': {
    eventKey: 'mewtwonite-legends-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Mewtwonite X & Y Distribution',
    description: 'Receive Mewtwonite X and Mewtwonite Y Mega Stones via Mystery Gift to unlock a special Mewtwo side mission in Pokémon Legends: Z-A!',
    rewardType: 'item',
    rewardName: 'Mewtwonite X & Mewtwonite Y',
    rewardDetails: {
      itemName: 'Mega Stones (2)',
      quantity: 2,
      unlocks: 'Mewtwo side mission in Lysandre Labs after completing main story',
      pokemonId: 150,
    },
    distributionMethod: 'internet',
    isOngoing: true,
    howToRedeem: {
      steps: [
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Get via Internet"',
        'Save your game',
        'After completing the main story, visit Lysandre Café',
        'Complete the side mission to catch Mewtwo with Mega Evolution access',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Get via Internet',
    },
    startDate: '2025-12-02T00:00:00-08:00',
    endDate: '2099-12-31T23:59:59-08:00', // Ongoing, no specific end date
    timezone: 'America/Los_Angeles',
    game: 'legends-za',
    youtubeVideos: ['TfC9Z_2DyI4'],
    officialLinks: [
      'https://www.pokemon.com/us/pokemon-news/mewtwo-mega-mewtwo-x-and-mega-mewtwo-y-debut-in-pokemon-legends-z-a',
    ],
    externalLinks: {
      officialAnnouncement: 'https://www.pokemon.com/us/pokemon-news/mewtwo-mega-mewtwo-x-and-mega-mewtwo-y-debut-in-pokemon-legends-z-a',
    },
  },
  'diancie-legends-za': {
    eventKey: 'diancie-legends-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Diancite Distribution',
    description: 'Receive Diancite Mega Stone via Mystery Gift to unlock a special Diancie side mission in Pokémon Legends: Z-A!',
    rewardType: 'item',
    rewardName: 'Diancite',
    rewardDetails: {
      itemName: 'Diancite Mega Stone',
      quantity: 1,
      unlocks: 'Diancie side mission after completing main story',
      pokemonId: 719,
    },
    distributionMethod: 'internet',
    isOngoing: true,
    howToRedeem: {
      steps: [
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Get via Internet"',
        'Save your game',
        'After completing the main story, check for the Diancie side mission',
        'Complete the side mission to catch Diancie with Mega Evolution access',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Get via Internet',
    },
    startDate: '2025-12-02T00:00:00-08:00',
    endDate: '2099-12-31T23:59:59-08:00',
    timezone: 'America/Los_Angeles',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: [
      'https://www.pokemon.com/us/pokemon-news/get-diancite-via-mystery-gift-and-diancie-in-pokemon-legends-z-a',
    ],
    externalLinks: {
      officialAnnouncement: 'https://www.pokemon.com/us/pokemon-news/get-diancite-via-mystery-gift-and-diancie-in-pokemon-legends-z-a',
    },
  },
  'ralts-gardevoirite-za': {
    eventKey: 'ralts-gardevoirite-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Ralts & Gardevoirite Distribution',
    description: 'Early purchase bonus! Receive a Ralts holding a Gardevoirite Stone via Mystery Gift in Pokémon Legends: Z-A!',
    rewardType: 'pokemon',
    rewardName: 'Ralts',
    rewardDetails: {
      species: 'Ralts',
      pokemonId: 280,
      heldItem: 'Gardevoirite Stone',
      isShiny: false,
    },
    distributionMethod: 'internet',
    isOngoing: false,
    howToRedeem: {
      steps: [
        'Purchase Pokémon Legends: Z-A before February 28, 2026',
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Get via Internet"',
        'Ralts will be added to your boxes',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Get via Internet',
    },
    startDate: '2025-12-02T00:00:00Z',
    endDate: '2026-02-28T23:59:59Z',
    timezone: 'UTC',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: ['https://legends.pokemon.com/en-us/news/early-purchase-bonuses'],
    externalLinks: {
      officialAnnouncement: 'https://legends.pokemon.com/en-us/news/early-purchase-bonuses',
    },
  },
  'pokeballs-digital-za': {
    eventKey: 'pokeballs-digital-za',
    eventType: EventType.MYSTERY_GIFT,
    title: '100 Poké Balls - Digital Edition Bonus',
    description: 'Purchase the digital version of Pokémon Legends: Z-A before February 28, 2026 to receive a code for 100 Poké Balls!',
    rewardType: 'item',
    rewardName: '100 Poké Balls',
    rewardDetails: {
      itemName: 'Poké Ball',
      quantity: 100,
    },
    distributionMethod: 'serial-code',
    serialCode: 'Unique code sent via email',
    isOngoing: false,
    howToRedeem: {
      steps: [
        'Purchase the digital version of Pokémon Legends: Z-A before February 28, 2026',
        'Check your email for the serial code',
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Receive Via Code"',
        'Enter your unique code',
        'Poké Balls will be placed in your bag',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Receive Via Code',
    },
    startDate: '2025-12-02T00:00:00Z',
    endDate: '2026-03-10T23:59:59Z',
    timezone: 'UTC',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: ['https://legends.pokemon.com/en-us/news/early-purchase-bonuses'],
    externalLinks: {
      officialAnnouncement: 'https://legends.pokemon.com/en-us/news/early-purchase-bonuses',
    },
  },
  'apricorn-balls-dlc-za': {
    eventKey: 'apricorn-balls-dlc-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Apricorn Balls - DLC Bonus',
    description: 'Purchase the digital edition of the Mega Dimension DLC to receive Fast, Heavy, Level, and Lure Balls (3 of each)!',
    rewardType: 'item',
    rewardName: 'Apricorn Balls',
    rewardDetails: {
      itemName: 'Special Poké Balls',
      quantity: 12,
      unlocks: '3x Fast Ball, 3x Heavy Ball, 3x Level Ball, 3x Lure Ball',
    },
    distributionMethod: 'serial-code',
    serialCode: 'Unique code sent via email',
    isOngoing: false,
    howToRedeem: {
      steps: [
        'Purchase the digital edition of Mega Dimension DLC',
        'Check your email for the serial code',
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Receive Via Code"',
        'Enter your unique code',
        'Poké Balls will be placed in your bag',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Receive Via Code',
    },
    startDate: '2025-12-11T00:00:00Z',
    endDate: '2026-03-10T23:59:59Z',
    timezone: 'UTC',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: [],
    externalLinks: {},
  },
  'audino-birthday-za': {
    eventKey: 'audino-birthday-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Birthday Cherish Ball Audino',
    description: 'Visit a Pokémon Center Store during your birthday month to receive a special Cherish Ball Audino! Available in Japan, Singapore, and Taiwan.',
    rewardType: 'pokemon',
    rewardName: 'Audino',
    rewardDetails: {
      species: 'Audino',
      pokemonId: 531,
      isShiny: false,
    },
    distributionMethod: 'serial-code',
    serialCode: 'Unique code given at Pokémon Center during birthday month',
    isOngoing: false,
    howToRedeem: {
      steps: [
        'Visit a Pokémon Center Store in Japan, Singapore, or Taiwan during your birthday month',
        'Receive your unique serial code',
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Receive Via Code"',
        'Enter your unique code',
        'Audino will be added to your boxes',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Receive Via Code',
    },
    startDate: '2025-12-02T00:00:00Z',
    endDate: '2026-10-31T23:59:59Z',
    timezone: 'UTC',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: [],
    externalLinks: {},
  },
  'slowpoke-japan-za': {
    eventKey: 'slowpoke-japan-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Cherish Ball Slowpoke - Japan Exclusive',
    description: 'Visit a Pokémon Center Store in Japan to receive a special Cherish Ball Slowpoke!',
    rewardType: 'pokemon',
    rewardName: 'Slowpoke',
    rewardDetails: {
      species: 'Slowpoke',
      pokemonId: 79,
      isShiny: false,
    },
    distributionMethod: 'serial-code',
    serialCode: 'Unique code given at Pokémon Center in Japan',
    isOngoing: false,
    howToRedeem: {
      steps: [
        'Visit a Pokémon Center Store in Japan',
        'Receive your unique serial code',
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Receive Via Code"',
        'Enter your unique code',
        'Slowpoke will be added to your boxes',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Receive Via Code',
    },
    startDate: '2025-12-02T00:00:00Z',
    endDate: '2025-11-30T23:59:59Z',
    timezone: 'UTC',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: [],
    externalLinks: {},
  },
  'retail-outfit-za': {
    eventKey: 'retail-outfit-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Retail Exclusive Outfit',
    description: 'Purchase Pokémon Legends: Z-A from select retailers to receive a unique outfit code with Trench Coat, Trousers, and Scarf!',
    rewardType: 'item',
    rewardName: 'Outfit Set',
    rewardDetails: {
      itemName: 'Special Outfit',
      quantity: 3,
      unlocks: 'Trench Coat, Trousers, Scarf',
    },
    distributionMethod: 'serial-code',
    serialCode: 'Unique code included with retail purchase',
    isOngoing: false,
    howToRedeem: {
      steps: [
        'Purchase Pokémon Legends: Z-A from select retailers',
        'Locate the unique code in your purchase',
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Receive Via Code"',
        'Enter your unique code',
        'Outfit items will be added to your wardrobe',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Receive Via Code',
    },
    startDate: '2025-12-02T00:00:00Z',
    endDate: '2026-02-28T23:59:59Z',
    timezone: 'UTC',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: [],
    externalLinks: {},
  },
  'retail-items-za': {
    eventKey: 'retail-items-za',
    eventType: EventType.MYSTERY_GIFT,
    title: 'Retail Exclusive Item Bundle',
    description: 'Purchase Pokémon Legends: Z-A from select retailers to receive helpful items including Super Potions, Revives, Full Heals, and a Rare Candy!',
    rewardType: 'item',
    rewardName: 'Item Bundle',
    rewardDetails: {
      itemName: 'Special Items',
      quantity: 29,
      unlocks: '20x Super Potion, 5x Revive, 3x Full Heal, 1x Rare Candy',
    },
    distributionMethod: 'serial-code',
    serialCode: 'Unique code included with retail purchase',
    isOngoing: false,
    howToRedeem: {
      steps: [
        'Purchase Pokémon Legends: Z-A from select retailers',
        'Locate the unique code in your purchase',
        'Open the main menu in Pokémon Legends: Z-A',
        'Select "Link Play"',
        'Select "Mystery Gift"',
        'Select "Receive Via Code"',
        'Enter your unique code',
        'Items will be placed in your bag',
      ],
      menuPath: 'Main Menu → Link Play → Mystery Gift → Receive Via Code',
    },
    startDate: '2025-12-02T00:00:00Z',
    endDate: '2026-02-28T23:59:59Z',
    timezone: 'UTC',
    game: 'legends-za',
    youtubeVideos: [],
    officialLinks: [],
    externalLinks: {},
  },
};
